### PR TITLE
Bugfix/fbfw 148 delete UI

### PR DESCRIPTION
**Pull request by justinyoocodazen**
The old code didn't show the delete ui upon entering the delete phase, or when refreshing when no delete orders were saved because it was checking the ordersMeta for orders with the destroy type. I switched the check to see if phases was build (which was already part of it) and if supply center count was lower than unit count (new).

### CODE REVIEW

**Review by sariacodazen — CHANGES_REQUESTED** [review]
Screen Shot 2022-05-19 at 12 04 43 PM
Screen Shot
<img width=
 2022-05-19 at 12 06 18 PM" src="https://user-images.githubusercontent.com/95884853/169382535-e62a084c-1372-4e07-b709-d80cb186b783.png">

Screen Shot 2022-05-19 at 12 05 43 PM

Screen Shot 2022-05-19 at 12 05 11 PM

I found a bug where if select to destroy and save, you can reselect it to cancel and save again. This forces legacy in a wait/postpone build state, then from there I was given the option to build a unit instead of destroy it (when I selected build at Naples it showed the building unit ui at Naples in beta). When I ran the game process, no unit was built, and the unit that was destroyed was not one I selected (nothing was selected to be destroyed, only building at Naples was sent through).

**Comment by sariacodazen** [comment]
I think a solution to this could be to not allow to save or ready unless a unit has been selected to destroy. I would double check with @bryancodazen

**Comment by sariacodazen** [comment]
Screen Shot 2022-05-19 at 12 13 57 PM
Forgot this last one. Its after I processed game. Notice how Italy still has 5 units (should have 4 now after destroy phase), and England has two new ones in London and Edi (built phase ended and their builds were successful)

**Comment by bryancodazen** [comment]
> The old code didn't show the delete ui upon entering the delete phase, or when refreshing when no delete orders were saved because it was checking the ordersMeta for orders with the destroy type. I switched the check to see if phases was build (which was already part of it) and if supply center count was lower than unit count (new).

This is a good way to check, but it would be better if we could make this global to be referenced in global state.

**Comment by bryancodazen** [comment]
> 

generally videos are a bit better to communicate these kinds of bugs

**Comment by bryancodazen** [comment]
> Screen Shot 2022-05-19 at 12 04 43 PM
> 
> Screen Shot &lt;img width=
> 
> 2022-05-19 at 12 06 18 PM" src="https://user-images.githubusercontent.com/95884853/169382535-e62a084c-1372-4e07-b709-d80cb186b783.png">
> Screen Shot 2022-05-19 at 12 05 43 PM
> 
> Screen Shot 2022-05-19 at 12 05 11 PM
> 
> I found a bug where if select to destroy and save, you can reselect it to cancel and save again. This forces legacy in a wait/postpone build state, then from there I was given the option to build a unit instead of destroy it (when I selected build at Naples it showed the building unit ui at Naples in beta). When I ran the game process, no unit was built, and the unit that was destroyed was not one I selected (nothing was selected to be destroyed, only building at Naples was sent through).

Pushed up some new code for this, I think the issue that caused this was that the builds UI was getting activated during destroys in the build phase. Can you please re-test this.

**Review by bryancodazen — APPROVED** [review]
lgtm

**Review by sariacodazen — APPROVED** [review]
Bug is gone; LGTM

**Pull request merged**
